import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { extractDrops, extractTotalCounts, gateReport, crossCheckMarkdownJson } from './mic-trend-gate.mjs';

// ============================================================================
// scripts/mic-trend-gate.test.ts — pin the artifact gate for the trend
// report. The gate's job: the committed report may ONLY declare zero
// two-burst drops. Fixtures prove the judgement fires in every tamper
// direction, and the last test reads the REAL committed report (the same
// artifact ci.yml's validate job gates on every push).
// ============================================================================

const GREEN_REPORT = `# Two-burst mic path — live pass-rate trend

**As of:** 2026-08-18 (UTC — regenerated by \`npm run refresh:mic-trend\`)
**Verdict:** the "first burst then dead" drop has **never fired in CI** since the
drain-stuck fix — **0 drops across 166 clean two-burst checks**.

## The trend

| Date (UTC) | mic-regression batches | verify:live voice stages | Two-burst drops |
|---|---|---|---|
| 2026-08-13 | **12/12** (2 batches) | 12 clean + 2 red* | 0 |
| 2026-08-14 | — | 20 clean (2 skipped†, 2 cancelled) | 0 |
| 2026-08-18 | 6/6 (manual) + **65/66** (11-batch burst: 10×6/6 + 1×5/6¶) | 6 clean | 0 |
| **Total** | **83/84** | **77 clean / 82** | **0** |

\\* a footnote line must never be read as a data row.
`;

// The JSON twin that must agree with GREEN_REPORT's Total row
// (batch 83/84 · voice 77 clean / 82 · 0 drops) and its three daily drops.
const GREEN_JSON = {
  totals: { batchPasses: 83, batchChecks: 84, voiceClean: 77, voiceRed: 5, drops: 0 },
  rows: [
    { date: '2026-08-13', drops: 0 },
    { date: '2026-08-14', drops: 0 },
    { date: '2026-08-18', drops: 0 },
  ],
};

describe('extractTotalCounts', () => {
  it('reads the Total row\'s batch and voice headline counts', () => {
    expect(extractTotalCounts(GREEN_REPORT)).toEqual({
      batchPasses: 83,
      batchChecks: 84,
      voiceClean: 77,
      voiceDenominator: 82,
    });
  });

  it('returns null when the Total row is missing or malformed', () => {
    expect(extractTotalCounts('no total here')).toBeNull();
    expect(extractTotalCounts(GREEN_REPORT.replace('**83/84**', '**??**'))).toBeNull();
  });
});

describe('crossCheckMarkdownJson', () => {
  it('agrees when the markdown and JSON twin match', () => {
    expect(crossCheckMarkdownJson(GREEN_REPORT, GREEN_JSON)).toEqual([]);
  });

  it('fails when the Total drops differ', () => {
    const red = GREEN_REPORT.replace('| **Total** | **83/84** | **77 clean / 82** | **0** |', '| **Total** | **83/84** | **77 clean / 82** | **2** |');
    expect(crossCheckMarkdownJson(red, GREEN_JSON).join('\n')).toContain('markdown **Total** drops 2 ≠ JSON totals.drops 0');
  });

  it('fails when the batch headline counts differ', () => {
    const drifted = GREEN_REPORT.replace('| **Total** | **83/84** |', '| **Total** | **83/90** |');
    expect(crossCheckMarkdownJson(drifted, GREEN_JSON).join('\n')).toContain('markdown batch 83/90 ≠ JSON totals 83/84');
  });

  it('fails when the voice headline counts differ', () => {
    const drifted = GREEN_REPORT.replace('**77 clean / 82**', '**77 clean / 90**');
    expect(crossCheckMarkdownJson(drifted, GREEN_JSON).join('\n')).toContain('markdown voice 77 clean / 90 ≠ JSON totals 77 clean / 82');
  });

  it('fails when a daily drops cell disagrees with its JSON row', () => {
    const red = GREEN_REPORT.replace('| 2026-08-14 | — | 20 clean (2 skipped†, 2 cancelled) | 0 |', '| 2026-08-14 | — | 20 clean (2 skipped†, 2 cancelled) | 3 |');
    expect(crossCheckMarkdownJson(red, GREEN_JSON).join('\n')).toContain('markdown day 2026-08-14 drops 3 ≠ JSON row drops 0');
  });

  it('fails when a date exists in one artifact but not the other', () => {
    const mdExtra = GREEN_REPORT.replace('| 2026-08-18 |', '| 2026-08-19 |');
    expect(crossCheckMarkdownJson(mdExtra, GREEN_JSON).join('\n')).toContain('markdown day 2026-08-19 has no JSON twin row');
    const jsonExtra = { ...GREEN_JSON, rows: [...GREEN_JSON.rows, { date: '2026-08-20', drops: 0 }] };
    expect(crossCheckMarkdownJson(GREEN_REPORT, jsonExtra).join('\n')).toContain('JSON row 2026-08-20 has no markdown day');
  });

  it('fails an unparseable or empty JSON twin', () => {
    expect(crossCheckMarkdownJson(GREEN_REPORT, null).join('\n')).toContain('cannot be cross-checked');
    expect(crossCheckMarkdownJson(GREEN_REPORT, {}).join('\n')).toContain('cannot be cross-checked');
  });
});

describe('extractDrops', () => {
  it('reads the Total row and every daily data row, ignoring footnotes and headers', () => {
    const { totalDrops, rows } = extractDrops(GREEN_REPORT);
    expect(totalDrops).toBe(0);
    expect(rows).toEqual([
      { date: '2026-08-13', drops: 0 },
      { date: '2026-08-14', drops: 0 },
      { date: '2026-08-18', drops: 0 },
    ]);
  });

  it('returns null totalDrops when the Total row is missing or malformed', () => {
    expect(extractDrops('no total here').totalDrops).toBeNull();
    // A Total row without a numeric drops cell must NOT parse as zero — a
    // report that can no longer state its drop count cannot be green.
    const broken = GREEN_REPORT.replace('| **0** |', '| **??** |');
    expect(extractDrops(broken).totalDrops).toBeNull();
  });
});

describe('gateReport', () => {
  it('passes a green report (Total equals the sum of its daily rows)', () => {
    const { ok, totalDrops, sumDrops, errors } = gateReport(GREEN_REPORT);
    expect(ok).toBe(true);
    expect(totalDrops).toBe(0);
    expect(sumDrops).toBe(0);
    expect(errors).toEqual([]);
  });

  it('fails when the Total row declares a drop (day rows zeroed — tamper direction 1)', () => {
    const red = GREEN_REPORT.replace('| **Total** | **83/84** | **77 clean / 82** | **0** |', '| **Total** | **83/84** | **77 clean / 82** | **1** |');
    const { ok, totalDrops, errors } = gateReport(red);
    expect(ok).toBe(false);
    expect(totalDrops).toBe(1);
    expect(errors.join('\n')).toContain('the Total row declares 1 two-burst drop(s), not 0');
  });

  it('fails when a daily row reports a drop (Total zeroed — tamper direction 2)', () => {
    const red = GREEN_REPORT.replace('| 2026-08-14 | — | 20 clean (2 skipped†, 2 cancelled) | 0 |', '| 2026-08-14 | — | 20 clean (2 skipped†, 2 cancelled) | 2 |');
    const { ok, errors } = gateReport(red);
    expect(ok).toBe(false);
    expect(errors.join('\n')).toContain('day 2026-08-14 reports 2 two-burst drop(s)');
  });

  it('lists every offending day, not just the first', () => {
    const red = GREEN_REPORT
      .replace('| 2026-08-13 | **12/12** (2 batches) | 12 clean + 2 red* | 0 |', '| 2026-08-13 | **12/12** (2 batches) | 12 clean + 2 red* | 1 |')
      .replace('| 2026-08-18 | 6/6 (manual) + **65/66** (11-batch burst: 10×6/6 + 1×5/6¶) | 6 clean | 0 |', '| 2026-08-18 | 6/6 (manual) + **65/66** (11-batch burst: 10×6/6 + 1×5/6¶) | 3 |');
    const { ok, errors } = gateReport(red);
    expect(ok).toBe(false);
    expect(errors.join('\n')).toContain('day 2026-08-13 reports 1 two-burst drop(s)');
    expect(errors.join('\n')).toContain('day 2026-08-18 reports 3 two-burst drop(s)');
  });

  it('fails when the Total row disagrees with the daily sum (Total zeroed, a day still red)', () => {
    const red = GREEN_REPORT.replace(
      '| 2026-08-14 | — | 20 clean (2 skipped†, 2 cancelled) | 0 |',
      '| 2026-08-14 | — | 20 clean (2 skipped†, 2 cancelled) | 2 |',
    );
    const { ok, totalDrops, sumDrops, errors } = gateReport(red);
    expect(ok).toBe(false);
    expect(totalDrops).toBe(0);
    expect(sumDrops).toBe(2);
    expect(errors.join('\n')).toContain('the **Total** row declares 0 drop(s) but the daily rows sum to 2 — the table is internally inconsistent');
  });

  it('fails when the Total row disagrees with the daily sum (a day zeroed, Total still red)', () => {
    const red = GREEN_REPORT.replace(
      '| **Total** | **83/84** | **77 clean / 82** | **0** |',
      '| **Total** | **83/84** | **77 clean / 82** | **1** |',
    );
    const { ok, totalDrops, sumDrops, errors } = gateReport(red);
    expect(ok).toBe(false);
    expect(totalDrops).toBe(1);
    expect(sumDrops).toBe(0);
    expect(errors.join('\n')).toContain('the **Total** row declares 1 drop(s) but the daily rows sum to 0 — the table is internally inconsistent');
  });

  it('does not flag a consistent red table as internally inconsistent', () => {
    // Total=2 with two days at 1 each: arithmetic is consistent, so the only
    // failures are the zero-rule (Total not 0) and the per-day drops — never
    // the inconsistency message.
    const red = GREEN_REPORT
      .replace('| 2026-08-13 | **12/12** (2 batches) | 12 clean + 2 red* | 0 |', '| 2026-08-13 | **12/12** (2 batches) | 12 clean + 2 red* | 1 |')
      .replace('| 2026-08-14 | — | 20 clean (2 skipped†, 2 cancelled) | 0 |', '| 2026-08-14 | — | 20 clean (2 skipped†, 2 cancelled) | 1 |')
      .replace('| **Total** | **83/84** | **77 clean / 82** | **0** |', '| **Total** | **83/84** | **77 clean / 82** | **2** |');
    const { ok, totalDrops, sumDrops, errors } = gateReport(red);
    expect(ok).toBe(false);
    expect(totalDrops).toBe(2);
    expect(sumDrops).toBe(2);
    expect(errors.join('\n')).not.toContain('internally inconsistent');
    expect(errors.join('\n')).toContain('the Total row declares 2 two-burst drop(s), not 0');
  });

  it('fails an unparseable report (no Total row, empty, or missing drops cell)', () => {
    expect(gateReport('')).toMatchObject({ ok: false });
    expect(gateReport('# no table here\n')).toMatchObject({ ok: false });
    const broken = GREEN_REPORT.replace('| **0** |', '| **??** |');
    expect(gateReport(broken).ok).toBe(false);
    expect(gateReport(broken).errors.join('\n')).toContain('no parseable **Total** row');
  });
});

describe('the committed report artifact', () => {
  it('is green right now (the same files ci.yml gates on every push)', () => {
    const markdown = readFileSync('docs/mic-regression-trend.md', 'utf8');
    const json = JSON.parse(readFileSync('docs/mic-regression-trend.json', 'utf8'));
    const { ok, errors } = gateReport(markdown);
    const crossErrors = crossCheckMarkdownJson(markdown, json);
    expect(ok, `the committed report must show zero drops: ${errors.join('; ')}`).toBe(true);
    expect(crossErrors, `the markdown must agree with its JSON twin: ${crossErrors.join('; ')}`).toEqual([]);
  });

  it('is wired as a runnable gate script with the exit-1 contract', () => {
    const gate = readFileSync('scripts/mic-trend-gate.mjs', 'utf8');
    expect(gate).toContain("const REPORT = join(ROOT, 'docs', 'mic-regression-trend.md');");
    expect(gate).toContain("const JSON_REPORT = join(ROOT, 'docs', 'mic-regression-trend.json');");
    expect(gate).toContain('crossCheckMarkdownJson(markdown, json)');
    expect(gate).toContain('process.exit(1)');
    expect(gate).toContain('the artifact must stay at 0');
  });
});
